fcacrm/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about, healthCheck
from userprofile.views import signup

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/properties/', include('property.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/brokers/', include('broker.urls')),
    path('dashboard/societies/', include('society.urls')),
    path('dashboard/processes/', include('process.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('sign-up/', signup, name='signup'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('health-check/', healthCheck),
]

lead/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.leads_list, name='leads_list'),
    path('<int:pk>/', views.leads_detail, name='leads_detail'),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path('<int:pk>/edit/', views.leads_edit, name='leads_edit'),
    path('<int:pk>/convert/', views.convert_to_client, name= 'leads_convert'),
    path('add-lead/', views.add_lead, name='add_lead'),

]

lead/models.py
from django.db import models
from django.contrib.auth.models import User

from broker.models import Broker
from property.models import Property

class Lead(models.Model):
    LEAD = 'Lead'
    PROSPECTO = 'Prospecto'
    CLIENT= 'Cliente'

    CHOICES_STATUS = (
        (LEAD, 'Lead'),
        (PROSPECTO, 'Prospecto'),
        (CLIENT, 'Cliente')
    )

    ABIERTO = 'Abierto'
    CERRADO = 'Cerrado'
    PERDIDO = 'Perdido'

    CHOICES_STATE = (
        (ABIERTO, 'Abierto'),
        (CERRADO, 'Cerrado'),
        (PERDIDO, 'Perdido')
    )

    BROKER = 'Broker'
    LETRERO = 'Letrero'
    COMPREOALQUILE = 'CompreoAlquile'
    CAMPAÑAINSTAGRAM = 'CampañaInstagram'
    Otro = 'Otro'
    

    CHOICES_FUENTE = (
        (BROKER, 'Broker'),
        (LETRERO, 'Letrero'),
        (COMPREOALQUILE, 'CompreoAlquile'),
        (CAMPAÑAINSTAGRAM, 'CampañaInstagram'),
        (Otro, 'Otro')
    )

    

    name = models.CharField(max_length=255)
    email = models.EmailField(blank=True, null=True)
    description = models.TextField(blank=True, null=True)
    phone = models.CharField(max_length=15,blank=True, null=True)
    property_interested = models.ForeignKey(Property, on_delete=models.SET_NULL, null=True, blank=True, related_name='interested_leads')
    broker = models.ForeignKey(Broker, on_delete=models.SET_NULL, null=True, blank=True, related_name='leads')
    fuente = models.CharField(max_length=30, choices=CHOICES_FUENTE, blank=True, null=True)
    status = models.CharField(max_length=10, choices=CHOICES_STATUS, default=LEAD)
    state = models.CharField(max_length=10, choices=CHOICES_STATE, default=ABIERTO)
    date= models.DateField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='leads', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name

lead/forms.py
from django import forms

from .models import Lead

class AddLeadForm(forms.ModelForm):
    class Meta:
        model= Lead
        fields=('name', 'email', 'description', 'phone', 'property_interested', 'broker', 'fuente','status','state','date')

        

lead/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from .forms import AddLeadForm
import datetime
from .models import Lead

from client.models import Client
from broker.models import Broker
from property.models import Property

@login_required
def leads_detail(request, pk):
    lead = Lead.objects.all().get(pk=pk)

    return render(request, 'lead/leads_detail.html', {'lead': lead})

@login_required
def leads_delete(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    lead.delete()

    messages.success(request, 'El Lead fue borrado exitosamente')

    return redirect('leads_list')

@login_required
def leads_list(request):
    state = request.GET.get('state', '')
    status = request.GET.get('status', '')
    month = request.GET.get('month', '')
    year = request.GET.get('year', '')

    leads = Lead.objects.all()
    if state:
        leads = leads.filter(state=state)
    if status:
        leads = leads.filter(status=status)
    if month:
        leads = leads.filter(date__month=month)
    if year:
        leads = leads.filter(date__year=year)

    current_year = datetime.datetime.now().year
    years = range(current_year - 5, current_year + 1)  # últimos 5 años hasta el año actual

    context = {
        'leads': leads,
        'states': Lead.CHOICES_STATE,
        'statuses': Lead.CHOICES_STATUS,
        'selected_state': state,
        'selected_status': status,
        'selected_month': month,
        'selected_year': year,
        'years': years
    }

    return render(request, 'lead/leads_list.html', context)


@login_required
def leads_edit(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    properties = Property.objects.all().order_by('name')  # Obtiene todas las propiedades disponibles
    brokers = Broker.objects.all().order_by('name')  # Obtiene todos los brokers disponibles

    if request.method == 'POST':
        form = AddLeadForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            messages.success(request, 'El Lead fue modificado exitosamente')
            return redirect('leads_list')
        else:
            messages.error(request, 'Error al modificar el Lead. Por favor, verifica los campos e intenta nuevamente.')
    else:
        form = AddLeadForm(instance=lead)

    context = {
        'form': form,
        'lead': lead,
        'properties': properties,  # Pasa las propiedades al contexto
        'brokers': brokers,  # Pasa los brokers al contexto
    }
    return render(request, 'lead/leads_edit.html', context)


@login_required
def add_lead(request):
    properties = Property.objects.all().order_by('name')
    brokers = Broker.objects.all().order_by('name')

    if request.method == 'POST':
        form = AddLeadForm(request.POST)
        if form.is_valid():
            lead = form.save(commit=False)
            lead.created_by = request.user
            lead.save()
            form.save_m2m()  # This is needed to save ManyToMany and ForeignKey fields when using commit=False

            messages.success(request, 'El Lead fue creado exitosamente')
            return redirect('leads_list')
        else:
            messages.error(request, 'Error al crear el Lead. Por favor, verifica los campos e intenta nuevamente.')
    else:
        form = AddLeadForm()

    context = {
        'form': form,
        'properties': properties,
        'brokers': brokers
    }
    return render(request, 'lead/add_lead.html', context)

@login_required
def convert_to_client(request, pk):
    lead = get_object_or_404(Lead, pk=pk)
    
    # Actualizar estado del lead
    lead.status = 'Cliente'
    lead.state = 'Cerrado'
    lead.save()

    # Guardar datos relevantes del lead en la sesión
    request.session['lead_to_client'] = {
        'commercialname': lead.name,
        'emailcontact': lead.email,
        'description': lead.description,
        'phonecontact': lead.phone,
        'broker_id': lead.broker.id if lead.broker else '',
    }

    request.session['coming_from_lead_conversion'] = True

    return redirect('/dashboard/clients/add-client/')

lead/templates/lead/add_lead.html
{% extends 'core/base.html' %}

{% block title %}Crear Prospecto{% endblock %} 

{% block content %}
<div class="mt-8 bg-white p-8 rounded-xl shadow-lg max-w-md mx-auto pt-4 border border-blue-900">
    <h1 class="text-3xl text-blue-900 mb-6">Crear Lead</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-4">
            <label for="name" class="block text-sm font-bold text-gray-700 mb-2">Nombre</label>
            <input type="text" id="name" name="name" class="w-full p-2 border border-gray-300 rounded" required>
        </div>

        <div class="mb-4">
            <label for="email" class="block text-sm font-bold text-gray-700 mb-2">Correo Electrónico</label>
            <input type="email" id="email" name="email" class="w-full p-2 border border-gray-300 rounded" >
        </div>

        <div class="mb-4">
            <label for="description" class="block text-sm font-bold text-gray-700 mb-2">Descripción</label>
            <textarea id="description" name="description" class="w-full p-2 border border-gray-300 rounded"></textarea>
        </div>

        <div class="mb-4">
            <label for="phone" class="block text-sm font-bold text-gray-700 mb-2">Teléfono</label>
            <input type="text" id="phone" name="phone" class="w-full p-2 border border-gray-300 rounded" >
        </div>

        <div class="mb-4">
            <label for="property_interested" class="block text-sm font-bold text-gray-700 mb-2">Propiedad de Interés</label>
            <select id="property_interested" name="property_interested" class="w-full p-2 border border-gray-300 rounded">
                <option value="">---------</option>
                {% for property in properties %}
                    <option value="{{ property.id }}">{{ property.name }}</option>
                {% endfor %}
            </select>
        </div>


        <div class="mb-4">
            <label for="broker" class="block text-sm font-bold text-gray-700 mb-2">Broker</label>
            <select id="broker" name="broker" class="w-full p-2 border border-gray-300 rounded">
                <option value="">---------</option>
                {% for broker in brokers %}
                    <option value="{{ broker.id }}">{{ broker.name }}</option>
                {% endfor %}
            </select>
        </div>


        <div class="mb-4">
            <label for="fuente" class="block text-sm font-bold text-gray-700 mb-2">Fuente </label>
            <select id="fuente" name="fuente" class="w-full p-2 border border-gray-300 rounded" required>
                {% for choice in form.fields.fuente.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-4">
            <label for="status" class="block text-sm font-bold text-gray-700 mb-2">Clasificación </label>
            <select id="status" name="status" class="w-full p-2 border border-gray-300 rounded" required>
                {% for choice in form.fields.status.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-4">
            <label for="state" class="block text-sm font-bold text-gray-700 mb-2">Estado </label>
            <select id="state" name="state" class="w-full p-2 border border-gray-300 rounded" required>
                {% for choice in form.fields.state.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Date -->
        <div class="mb-4">
            <label for="date" class="block text-sm font-bold text-gray-700 mb-2">Fecha de Ingreso </label>
            <input type="date" id="date" name="date" class="w-full p-2 border border-gray-300 rounded" required>
        </div>

        <div class="flex items-center justify-center mt-4">
            <button class="py-2 px-4 bg-blue-900 hover:bg-blue-700 text-sm text-white rounded-full" type="submit">Crear</button>
        </div>
    </form>
</div>



{% endblock %}

lead/templates/lead/leads_detail.html
{% extends 'core/base.html' %}

{% block title %}{{lead.name}}{% endblock %} 

{% block content %}
<div class="mt-8 mx-auto max-w-4xl">
    <div class="bg-white rounded-xl shadow-lg overflow-hidden">
        <div class="p-8">
            <h1 class="text-4xl font-bold text-blue-900 mb-6">{{ lead.name }}</h1>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="space-y-4">
                    {% if lead.description %}
                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Descripción</h2>
                        <p class="text-gray-600">{{ lead.description }}</p>
                    </div>
                    {% endif %}

                    {% if lead.email %}
                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Correo Electrónico</h2>
                        <p class="text-gray-600">{{ lead.email }}</p>
                    </div>
                    {% endif %}

                    {% if lead.phone %}
                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Teléfono</h2>
                        <p class="text-gray-600">{{ lead.phone }}</p>
                    </div>
                    {% endif %}

                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Propiedad de Interés</h2>
                        <p class="text-gray-600">{{ lead.property_interested }}</p>
                    </div>

                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Broker</h2>
                        <p class="text-gray-600">{{ lead.broker }}</p>
                    </div>

                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Fuente</h2>
                        <p class="text-gray-600">{{ lead.fuente }}</p>
                    </div>
                </div>

                <div class="space-y-4">
                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Clasificación </h2>
                        <p class="text-gray-600">{{ lead.get_status_display }}</p>
                    </div>

                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Estado </h2>
                        <p class="text-gray-600">{{ lead.get_state_display }}</p>
                    </div>

                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Fecha de Ingreso</h2>
                        <p class="text-gray-600">{{ lead.date }}</p>
                    </div>
                </div>
            </div>

            <!-- Action buttons aligned to the bottom -->
            <div class="flex justify-end space-x-4 mt-4">
                <a href="{% url 'leads_edit' lead.id %}" class="bg-blue-900 hover:bg-blue-700 text-white py-2 px-4 rounded transition duration-300">Modificar</a>
                <a href="{% url 'leads_convert' lead.id %}" class="bg-green-900 hover:bg-green-700 text-white py-2 px-4 rounded transition duration-300">Convertir a Cliente</a> 
                <a href="{% url 'leads_delete' lead.id %}" class="bg-red-600 hover:bg-red-700 text-white py-2 px-4 rounded transition duration-300">Borrar</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

lead/templates/lead/leads_edit.html
{% extends 'core/base.html' %}

{% block title %}Modificar Lead{% endblock %} 

{% block content %}
<div class="mt-8 bg-white p-8 rounded-xl shadow-lg max-w-md mx-auto pt-4 border border-blue-900">
    <h1 class="text-3xl text-blue-900 mb-6">Modificar Lead</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-4">
            <label for="name" class="block text-sm font-bold text-gray-700 mb-2">Nombre</label>
            <input type="text" id="name" name="name" class="w-full p-2 border border-gray-300 rounded" value="{{ form.instance.name }}" required>
        </div>

        <div class="mb-4">
            <label for="email" class="block text-sm font-bold text-gray-700 mb-2">Correo Electrónico</label>
            <input type="email" id="email" name="email" class="w-full p-2 border border-gray-300 rounded" {% if form.instance.email is not None %} value="{{ form.instance.email }}" {% endif %}>
        </div>

        <div class="mb-4">
            <label for="description" class="block text-sm font-bold text-gray-700 mb-2">Descripción</label>
            <textarea id="description" name="description" class="w-full p-2 border border-gray-300 rounded">{{ form.instance.description }}</textarea>
        </div>

        <div class="mb-4">
            <label for="phone" class="block text-sm font-bold text-gray-700 mb-2">Teléfono</label>
            <input type="text" id="phone" name="phone" class="w-full p-2 border border-gray-300 rounded" {% if form.instance.phone is not None %} value="{{ form.instance.phone }}" {% endif %} >
        </div>

        <div class="mb-4">
            <label for="property_interested" class="block text-sm font-bold text-gray-700 mb-2">Propiedad de Interés</label>
            <select id="property_interested" name="property_interested" class="w-full p-2 border border-gray-300 rounded">
                {% for property in properties %}
                    <option value="{{ property.id }}" {% if property.id == form.instance.property_interested.id %}selected{% endif %}>{{ property.name }}</option>
                {% endfor %}
            </select>
        </div>
        
        <div class="mb-4">
            <label for="broker" class="block text-sm font-bold text-gray-700 mb-2">Broker</label>
            <select id="broker" name="broker" class="w-full p-2 border border-gray-300 rounded">
                <option value="">---------</option>
                {% for broker in brokers %}
                    <option value="{{ broker.id }}" {% if broker.id == form.instance.broker.id %}selected{% endif %}>{{ broker.name }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-4">
            <label for="fuente" class="block text-sm font-bold text-gray-700 mb-2">Fuente </label>
            <select id="fuente" name="fuente" class="w-full p-2 border border-gray-300 rounded">
                {% for choice in form.fields.fuente.choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 == form.instance.fuente %}selected{% endif %}>{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>
        

        <div class="mb-4">
            <label for="status" class="block text-sm font-bold text-gray-700 mb-2">Clasificación</label>
            <select id="status" name="status" class="w-full p-2 border border-gray-300 rounded">
                {% for choice in form.fields.status.choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 == form.instance.status %}selected{% endif %}>{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <div class="mb-4">
            <label for="state" class="block text-sm font-bold text-gray-700 mb-2">Estado</label>
            <select id="state" name="state" class="w-full p-2 border border-gray-300 rounded">
                {% for choice in form.fields.state.choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 == form.instance.state %}selected{% endif %}>{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

            <!-- Date -->
            <div class="mb-4">
                <label for="date" class="block text-sm font-bold text-gray-700 mb-2">Fecha de Ingreso</label>
                <input type="date" id="date" name="date" class="w-full p-2 border border-gray-300 rounded" value="{% if form.instance.date %}{{ form.instance.date|date:'Y-m-d' }}{% endif %}" required>
            </div>

        <div class="flex items-center justify-center mt-4">
            <button class="py-2 px-4 bg-blue-900 hover:bg-blue-700 text-sm text-white rounded-full" type="submit">Modificar</button>
        </div>
    </form>
</div>





{% endblock %}

lead/templates/lead/leads_list.html
{% extends 'core/base.html' %}

{% block title %}Leads{% endblock %}

{% block content %}
<div class="mt-8 bg-white p-8 rounded-xl shadow-md mx-auto pt-4 overflow-x-auto border border-blue-900 max-w-6xl w-full">
    <h1 class="text-3xl text-blue-900 mb-6">Leads</h1>

    <!-- Formulario de Filtros y Botón de Crear Lead en la misma fila -->
    <div class="flex flex-wrap items-end justify-between mb-4">
        <!-- Botón Crear Lead -->
        <a href="{% url 'add_lead' %}" class="py-2 px-4 bg-blue-900 hover:bg-blue-700 rounded-full text-white mb-3">Crear Lead</a>

        <form action="" method="get" class="flex flex-wrap items-end">
            
            <div class="mr-2">
                <label for="year" class="block tracking-wide text-gray-700 text-xs font-bold mb-2">Año</label>
                <select name="year" id="year" class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
                    <option value="">Todos</option>
                    {% for year in years %}
                    <option value="{{ year }}" {% if selected_year|stringformat:"s" == year|stringformat:"s" %}selected{% endif %}>{{ year }}</option>
                    {% endfor %}
                </select>
            </div>

            <div class="mr-2">
                <label for="month" class="block tracking-wide text-gray-700 text-xs font-bold mb-2">Mes</label>
                <select name="month" id="month" class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
                    <option value="">Todos</option>
                    <option value="1" {% if selected_month == '1' %}selected{% endif %}>Enero</option>
                    <option value="2" {% if selected_month == '2' %}selected{% endif %}>Febrero</option>
                    <option value="3" {% if selected_month == '3' %}selected{% endif %}>Marzo</option>
                    <option value="4" {% if selected_month == '4' %}selected{% endif %}>Abril</option>
                    <option value="5" {% if selected_month == '5' %}selected{% endif %}>Mayo</option>
                    <option value="6" {% if selected_month == '6' %}selected{% endif %}>Junio</option>
                    <option value="7" {% if selected_month == '7' %}selected{% endif %}>Julio</option>
                    <option value="8" {% if selected_month == '8' %}selected{% endif %}>Agosto</option>
                    <option value="9" {% if selected_month == '9' %}selected{% endif %}>Septiembre</option>
                    <option value="10" {% if selected_month == '10' %}selected{% endif %}>Octubre</option>
                    <option value="11" {% if selected_month == '11' %}selected{% endif %}>Noviembre</option>
                    <option value="12" {% if selected_month == '12' %}selected{% endif %}>Diciembre</option>
                </select>
            </div>



            <div class="mr-2">
                <label for="state" class="block tracking-wide text-gray-700 text-xs font-bold mb-2">Estado</label>
                <select name="state" id="state" class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
                    <option value="">Todos</option>
                    {% for value, readable_name in states %}
                        <option value="{{ value }}" {% if selected_state == value %}selected{% endif %}>{{ readable_name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="mr-2">
                <label for="status" class="block tracking-wide text-gray-700 text-xs font-bold mb-2">Clasificación</label>
                <select name="status" id="status" class="block appearance-none w-full bg-white border border-gray-400 hover:border-gray-500 px-4 py-2 pr-8 rounded shadow leading-tight focus:outline-none focus:shadow-outline">
                    <option value="">Todos</option>
                    {% for value, readable_name in statuses %}
                        <option value="{{ value }}" {% if selected_status == value %}selected{% endif %}>{{ readable_name }}</option>
                    {% endfor %}
                </select>
            </div>
            <!-- Botón Filtrar dentro del formulario -->
            <button type="submit" class="py-2 px-4 bg-blue-900 hover:bg-blue-700 rounded-full text-white">Filtrar</button>
        </form>
    </div>

    <!-- Listado de Leads -->
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-4 gap-6 mt-6">
        {% for lead in leads %}
            <a href="{% url 'leads_detail' lead.id %}" class="bg-gray-100 hover:bg-gray-200 p-4 rounded-md">
                <img src="https://img.freepik.com/premium-vector/man-talking-phone-male-character_316839-4368.jpg" alt="{{ lead.name }}" class="w-full h-40 object-cover object-center mb-4 rounded-md">
                <h2 class="text-blue-900 text-lg font-semibold">{{ lead.name }}</h2>
                <p class="text-gray-700">{{ lead.status }}</p>
                <p class="text-gray-700">{{ lead.state }}</p>
                <p class="text-gray-700">{{ lead.date }}</p>
            </a>
        {% endfor %}
    </div>
</div>
{% endblock %}