fcacrm/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include

from core.views import index, about, healthCheck
from userprofile.views import signup

urlpatterns = [
    path('', index, name='index'),
    path('dashboard/leads/', include('lead.urls')),
    path('dashboard/properties/', include('property.urls')),
    path('dashboard/clients/', include('client.urls')),
    path('dashboard/brokers/', include('broker.urls')),
    path('dashboard/societies/', include('society.urls')),
    path('dashboard/processes/', include('process.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('about/', about, name='about'),
    path('sign-up/', signup, name='signup'),
    path('log-in/', views.LoginView.as_view(template_name='userprofile/login.html'), name='login'),
    path('log-out/', views.LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('health-check/', healthCheck),
]

lead/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.leads_list, name='leads_list'),
    path('<int:pk>/', views.leads_detail, name='leads_detail'),
    path('<int:pk>/delete/', views.leads_delete, name='leads_delete'),
    path('<int:pk>/edit/', views.leads_edit, name='leads_edit'),
    path('<int:pk>/convert/', views.convert_to_client, name= 'leads_convert'),
    path('add-lead/', views.add_lead, name='add_lead'),

]

property/urls.py
from django.urls import path

from . import views

urlpatterns=[
    path('', views.properties_list, name='properties_list'),
    path('<int:pk>/', views.properties_detail, name='properties_detail'),
    path('<int:pk>/delete/', views.properties_delete, name='properties_delete'),
    path('<int:pk>/edit/', views.properties_edit, name='properties_edit'),
    path('add-property/', views.add_property, name='add_property'),

]

property/models.py
from django.db import models
from django.contrib.auth.models import User
from society.models import Society
from client.models import Client
from datetime import date

class Property(models.Model):
    GOOD = 'Bueno'
    REPAIR = 'A Reparar'

    CHOICES_CONDITION = (
        (GOOD, 'Bueno'),
        (REPAIR, 'A Reparar'),
    )

    DISPONIBLE = 'Disponible'
    OCUPADO = 'Ocupado'

    CHOICES_STATE = (
        (DISPONIBLE, 'Disponible'),
        (OCUPADO, 'Ocupado'),
    )

    ENERO= 'Enero'
    FEBRERO='Febrero'
    MARZO='Marzo'
    ABRIL='Abril'
    MAYO='Mayo'
    JUNIO='Junio'
    JULIO='Julio'
    AGOSTO='Agosto'
    SEPTIEMBRE='Septiembre'
    OCTUBRE='Octubre'
    NOVIEMBRE='Noviembre'
    DICIEMBRE='Diciembre'

    CHOICES_MONTHS = (
        (ENERO, 'Enero'),
        (FEBRERO, 'Febrero'),
        (MARZO, 'Marzo'),
        (ABRIL, 'Abril'),
        (MAYO, 'Mayo'),
        (JUNIO, 'Junio'),
        (JULIO, 'Julio'),
        (AGOSTO, 'Agosto'),
        (SEPTIEMBRE, 'Septiembre'),
        (OCTUBRE, 'Octubre'),
        (NOVIEMBRE, 'Noviembre'),
        (DICIEMBRE, 'Diciembre'),
    )

    FCA='FCA'
    ADMINISTRACION='Administracion'

    PAYOPTIONS = (
        (FCA,'FCA'),
        (ADMINISTRACION, 'Administracion'),
    )

    SI = 'SI'
    NO = 'NO'

    POLIZAOPTIONS = (
        (SI,'SI'),
        (NO, 'NO'),
    )

    name = models.CharField(max_length=255)
    society = models.ForeignKey(Society, related_name='properties', on_delete=models.CASCADE, null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    state = models.CharField(max_length=10, choices=CHOICES_STATE, default=DISPONIBLE)
    currentlease = models.ForeignKey(Client, related_name='properties', on_delete=models.SET_NULL, null=True, blank=True)
    condition = models.CharField(max_length=10, choices=CHOICES_CONDITION, default=GOOD)
    parkings = models.IntegerField(default=0)
    area1 = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    address = models.CharField(max_length=255, blank=True, null=True)
    admin=models.CharField(max_length=255, blank=True, null=True)
    adminemail=models.EmailField(blank=True, null=True)
    adminphone=models.CharField(max_length=15,blank=True, null=True)
    rentprice = models.DecimalField(max_digits=20, decimal_places=2, default=0.0)
    mainteinprice = models.DecimalField(max_digits=20, decimal_places=2, default=0.0)
    costxm2 = models.DecimalField(max_digits=10, decimal_places=2,  default= 0.0)
    maintxm2 = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)
    maindescrp = models.TextField(blank=True, null=True)
    pay = models.CharField(max_length=20, choices=PAYOPTIONS, blank=True, null=True)
    poliza = models.CharField(max_length=20, choices=POLIZAOPTIONS, blank=True, null=True)
    deposit= models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)
    leasestart = models.DateField(blank=True, null=True)
    leasend = models.DateField(blank=True, null=True)
    increase = models.DecimalField(max_digits=10, decimal_places=2,blank=True, null=True)
    lastincrease = models.DateField(blank=True, null=True)
    renov = models.CharField(max_length=255, choices=CHOICES_MONTHS, blank=True, null=True)
    notifyrenew = models.IntegerField(blank=True, null=True)
    created_by = models.ForeignKey(User, related_name='properties', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    @classmethod
    def update_prices(cls):
        # Obtiene todas las instancias de Property
        all_properties = cls.objects.all()
        for property in all_properties:
            if property.lastincrease is not None and property.increase is not None:
                current_year = date.today().year
                last_increase_year = property.lastincrease.year

                # Verifica si el último aumento no fue en el año actual
                if last_increase_year < current_year:
                    # Calcula los nuevos valores incrementados
                    property.costxm2 = (property.costxm2 * property.increase) + property.costxm2
                    property.maintxm2 = (property.maintxm2 * property.increase) + property.maintxm2
                    property.rentprice = property.costxm2 * property.area1
                    property.mainteinprice = property.maintxm2 * property.area1
                    # Actualiza la fecha de último aumento al día actual
                    property.lastincrease = date.today()
                    # Guarda los cambios en el modelo
                    property.save()

    def __str__(self):
        return self.name

property/forms.py
from django import forms
from .models import Property  

class AddPropertyForm(forms.ModelForm):
    class Meta:
        model = Property
        fields = (
            'name', 
            'description',
            'state',
            'condition',
            'society',
            'parkings', 
            'area1', 
            'address',
            'admin',
            'adminemail',
            'adminphone',
            'rentprice',
            'mainteinprice',
            'maindescrp',
            'pay',
            'poliza',
            'deposit',
            'lastincrease',
            'currentlease',
            'leasestart',
            'leasend',
            'increase',
            'renov',
            'notifyrenew',
        )

property/views.py
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import get_object_or_404, render, redirect
from datetime import date

from society.models import Society
from client.models import Client
from .forms import AddPropertyForm
from .models import Property

@login_required
def properties_detail(request, pk):
    property = get_object_or_404(Property, pk=pk)

    return render(request, 'property/properties_detail.html', {
        'property': property
    })

@login_required
def properties_delete(request, pk):
    property = get_object_or_404(Property, pk=pk)
    property.delete()

    messages.success(request, 'La Propiedad fue borrada exitosamente')

    return redirect('properties_list')

@login_required
def properties_list(request):
    Property.update_prices()
    properties = Property.objects.all()

    return render(request, 'property/properties_list.html', {'properties': properties})


@login_required
def properties_edit(request, pk):
    property = get_object_or_404(Property, pk=pk)
    societies = Society.objects.all()
    clients = Client.objects.all()  # Fetch all clients

    if request.method == 'POST':
        form = AddPropertyForm(request.POST, instance=property)

        if form.is_valid():
            property = form.save(commit=False)

            if property.increase is None:
                property.increase=0

            if property.area1 != 0:
                 property.costxm2 = property.rentprice/property.area1
                 property.maintxm2 = property.mainteinprice/property.area1  
            else:
                property.costxm2 = 0
                property.maintxm2 = 0 

            if property.state == 'Disponible':
                # Set fields to None
                property.currentlease = None
                property.pay = None
                property.leasestart = None
                property.leasend = None
                property.increase = 0
                property.lastincrease= None
                property.renov = None
                property.notifyrenew = 0
                property.poliza=None
                property.deposit= 0
            
            # Save the property after making all changes
            property.save()

            messages.success(request, 'La Propiedad fue modificada exitosamente')
            return redirect('properties_list')
        else:
            print(form.errors)
            messages.error(request, 'Error al modificar la Propiedad. Por favor, revisa los errores en el formulario.')
    else:
        form = AddPropertyForm(instance=property)

    return render(request, 'property/properties_edit.html', {'form': form, 'societies': societies, 'clients': clients})

@login_required
def add_property(request):
    societies = Society.objects.all()  # Obtain all existing societies
    clients = Client.objects.all()  # Fetch all clients

    if request.method == 'POST':
        form = AddPropertyForm(request.POST)

        if form.is_valid():
            property = form.save(commit=False)
            property.created_by = request.user

            if property.increase is None:
                property.increase=0

            if property.area1 != 0:
                 property.costxm2 = property.rentprice/property.area1
                 property.maintxm2 = property.mainteinprice/property.area1  
            else:
                property.costxm2 = 0
                property.maintxm2 = 0     

            property.save()

            messages.success(request, 'La Propiedad fue creada exitosamente')

            return redirect('properties_list')
        else:
            # Add error messages in Spanish
            messages.error(request, 'Error al crear la Propiedad. Por favor, revisa los errores en el formulario.')
    else:
        form = AddPropertyForm()

    return render(request, 'property/add_property.html', {'form': form, 'societies': societies, 'clients': clients})

property/templates/property/add_property.html
{% extends 'core/base.html' %}

{% block title %}Crear Propiedad{% endblock %}

{% block content %}
<div class="mt-8 bg-white p-8 rounded-xl shadow-lg max-w-md mx-auto pt-4 border border-blue-900">
    <h1 class="text-3xl text-blue-900 mb-6">Crear Propiedad</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <!-- Nombre -->
        <div class="mb-4">
            <label for="name" class="block text-sm font-bold text-gray-700 mb-2">Nombre</label>
            <input type="text" id="name" name="name" class="w-full p-2 border border-gray-300 rounded" required>
        </div>


        <!-- Sociedad -->
        <div class="mb-4">
            <label for="society" class="block text-sm font-bold text-gray-700 mb-2">Sociedad</label>
            <select id="society" name="society" class="w-full p-2 border border-gray-300 rounded" >
                <option value="">---------</option>
                {% for society in societies %}
                    <option value="{{ society.id }}">{{ society.name }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Descripción -->
        <div class="mb-4">
            <label for="description" class="block text-sm font-bold text-gray-700 mb-2">Descripción </label>
            <textarea id="description" name="description" class="w-full p-2 border border-gray-300 rounded"></textarea>
        </div>

        <!-- Condición -->
        <div class="mb-4">
            <label for="condition" class="block text-sm font-bold text-gray-700 mb-2">Condición</label>
            <select id="condition" name="condition" class="w-full p-2 border border-gray-300 rounded" required>
                {% for choice in form.fields.condition.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <!--Administrador -->
        <div class="mb-4">
            <label for="admin" class="block text-sm font-bold text-gray-700 mb-2">Administrador</label>
            <input type="text" id="admin" name="admin" class="w-full p-2 border border-gray-300 rounded" >
        </div>

        <div class="mb-4">
            <label for="adminemail" class="block text-sm font-bold text-gray-700 mb-2">Correo Electrónico Administrador</label>
            <input type="email" id="adminemail" name="adminemail" class="w-full p-2 border border-gray-300 rounded" >
        </div>

        <div class="mb-4">
            <label for="adminphone" class="block text-sm font-bold text-gray-700 mb-2">Teléfono Administrador </label>
            <input type="text" id="phone" name="adminphone" class="w-full p-2 border border-gray-300 rounded" >
        </div>

        <!-- Estacionamientos -->
        <div class="mb-4">
            <label for="parkings" class="block text-sm font-bold text-gray-700 mb-2">Estacionamientos</label>
            <input type="number" id="parkings" name="parkings" class="w-full p-2 border border-gray-300 rounded" required>
        </div>

        <!-- Área -->
        <div class="mb-4">
            <label for="area1" class="block text-sm font-bold text-gray-700 mb-2">Área (m²)</label>
            <input type="text" id="area1" name="area1" class="w-full p-2 border border-gray-300 rounded" required>
        </div>

        <!-- Dirección -->
        <div class="mb-4">
            <label for="address" class="block text-sm font-bold text-gray-700 mb-2">Dirección</label>
            <input type="text" id="address" name="address" class="w-full p-2 border border-gray-300 rounded">
        </div>


        <!-- Precio de Alquiler  -->
        <div class="mb-4">
            <label for="rentprice" class="block text-sm font-bold text-gray-700 mb-2">Precio de Alquiler</label>
            <input type="text" id="rentprice" name="rentprice" class="w-full p-2 border border-gray-300 rounded" required>
        </div>

        <!-- Precio de Mantenimiento -->
        <div class="mb-4">
            <label for="mainteinprice" class="block text-sm font-bold text-gray-700 mb-2">Precio de Mantenimiento</label>
            <input type="text" id="mainteinprice" name="mainteinprice" class="w-full p-2 border border-gray-300 rounded" required>
        </div>


        <!-- Descripción del Mantenimiento -->
        <div class="mb-4">
            <label for="maindescrp" class="block text-sm font-bold text-gray-700 mb-2">Descripción del Mantenimiento </label>
            <textarea id="maindescrp" name="maindescrp" class="w-full p-2 border border-gray-300 rounded"></textarea>
        </div>


        <!-- Estado -->
        <div class="mb-4">
            <label for="state" class="block text-sm font-bold text-gray-700 mb-2">Estado</label>
            <select id="state" name="state" class="w-full p-2 border border-gray-300 rounded" oninput="toggleAdditionalOptions()" required>
                {% for choice in form.fields.state.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Additional options -->
        <div id="additionalOptions" style="display: none;">

        <!-- Inquilino -->
        <div class="mb-4">
            <label for="currentlease" class="block text-sm font-bold text-gray-700 mb-2">Inquilino </label>
            <select id="currentlease" name="currentlease" class="w-full p-2 border border-gray-300 rounded" >
                <option value="">---------</option>
                {% for client in clients %}
                    <option value="{{ client.id }}">{{ client.commercialname }}</option>
                {% endfor %}
            </select>
        </div>


        <!-- Fecha Último incremento -->
        <div class="mb-4">
            <label for="lastincrease" class="block text-sm font-bold text-gray-700 mb-2">Fecha Último Incremento (Si es nuevo contrato dejar fecha actual) </label>
            <input type="date" id="lastincrease" name="lastincrease" class="w-full p-2 border border-gray-300 rounded">
        </div>


        <!-- Pago Mantenimiento -->
        <div class="mb-4">
            <label for="pay" class="block text-sm font-bold text-gray-700 mb-2">Pago de Mantenimiento </label>
            <select id="pay" name="pay" class="w-full p-2 border border-gray-300 rounded" >
                {% for choice in form.fields.pay.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Poliza -->
        <div class="mb-4">
            <label for="poliza" class="block text-sm font-bold text-gray-700 mb-2">Póliza</label>
            <select id="poliza" name="poliza" class="w-full p-2 border border-gray-300 rounded" >
                {% for choice in form.fields.poliza.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Depósito -->
        <div class="mb-4">
            <label for="deposit" class="block text-sm font-bold text-gray-700 mb-2">Depósito </label>
            <input type="text" id="deposit" name="deposit" class="w-full p-2 border border-gray-300 rounded" >
        </div>

        <!-- Inicio del arrendamiento -->
        <div class="mb-4">
            <label for="leasestart" class="block text-sm font-bold text-gray-700 mb-2">Inicio del Contrato </label>
            <input type="date" id="leasestart" name="leasestart" class="w-full p-2 border border-gray-300 rounded">
        </div>

        <!-- Fin del arrendamiento -->
        <div class="mb-4">
            <label for="leasend" class="block text-sm font-bold text-gray-700 mb-2">Fin del Contrato </label>
            <input type="date" id="leasend" name="leasend" class="w-full p-2 border border-gray-300 rounded">
        </div>

        <!-- Increase -->
        <div class="mb-4">
            <label for="increase" class="block text-sm font-bold text-gray-700 mb-2">Incremento </label>
            <input type="text" id="increase" name="increase" class="w-full p-2 border border-gray-300 rounded" >
        </div>

        <!-- Mes de Renovación -->
        <div class="mb-4">
            <label for="renov" class="block text-sm font-bold text-gray-700 mb-2">Mes de Renovación </label>
            <select id="renov" name="renov" class="w-full p-2 border border-gray-300 rounded">
                {% for choice in form.fields.renov.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
                {% endfor %}
            </select>
        </div>

        <!-- Notificar Renovación -->
        <div class="mb-4">
            <label for="notifyrenew" class="block text-sm font-bold text-gray-700 mb-2">Días Notificar Renovación</label>
            <select id="notifyrenew" name="notifyrenew" class="w-full p-2 border border-gray-300 rounded">
                <option value=""></option>
                <option value="60">60</option>
                <option value="80">80</option>
                <option value="90">90</option>
                <option value="180">180</option>
            </select>
        </div>

        </div>

        <!-- Botón de envío -->
        <div class="flex items-center justify-center mt-4">
            <button class="py-2 px-4 bg-blue-900 hover:bg-blue-700 text-white rounded-full" type="submit">Crear</button>
        </div>
        </form>

        <script>
            function toggleAdditionalOptions() {
                var stateField = document.getElementById('state');
                var additionalOptionsDiv = document.getElementById('additionalOptions');
            
                if (stateField.value === 'Ocupado') {
                    additionalOptionsDiv.style.display = 'block';
                } else {
                    additionalOptionsDiv.style.display = 'none';
                }
            }
            </script>
            
        </div>

        {% endblock %}

property/templates/property/properties_detail.html
{% extends 'core/base.html' %}

{% block title %}{{ property.name }}{% endblock %} 

{% block content %}
<div class="mt-8 mx-auto max-w-4xl">
    <div class="bg-white rounded-xl shadow-lg overflow-hidden">
        <div class="p-8">
            <h1 class="text-4xl font-bold text-blue-900 mb-6">{{ property.name }}</h1>
            <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
                <div class="space-y-4">
                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Información General</h2>
                        {% if property.society %}
                        <p class="text-gray-600">Sociedad: {{ property.society }}</p>
                        {% endif %}
                        <p class="text-gray-600">Estado: {{ property.get_state_display }}</p>
                        <p class="text-gray-600">Condición: {{ property.get_condition_display }}</p>
                        {% if property.description %}
                        <p class="text-gray-600">Descripción: {{ property.description }}</p>
                        {% endif %}
                        {% if property.admin %}
                        <p class="text-gray-600">Administrador: {{ property.admin }}</p>
                        {% endif %}
                        {% if property.adminemail %}
                        <p class="text-gray-600">Correo Administrador: {{ property.adminemail }}</p>
                        {% endif %}
                        {% if property.adminphone %}
                        <p class="text-gray-600">Teléfono Administrador: {{ property.adminphone }}</p>
                        {% endif %}
                    </div>
                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Detalles del Inmueble</h2>
                        <p class="text-gray-600">Parqueaderos: {{ property.parkings }}</p>
                        <p class="text-gray-600">Área: {{ property.area1 }} m²</p>
                        {% if property.address%}
                        <p class="text-gray-600">Dirección: {{ property.address }}</p>
                        {% endif %}
                    </div>
                </div>

                <div class="space-y-4">
                    <div>
                        <h2 class="text-xl font-semibold text-blue-900">Precios</h2>
                        <p class="text-gray-600">Renta: {{ property.rentprice }}</p>
                        <p class="text-gray-600">Mantenimiento: {{ property.mainteinprice }}</p>
                        <p class="text-gray-600">Precio por m²: {{ property.costxm2 }}</p>
                        <p class="text-gray-600">Mantenimiento por m²: {{ property.maintxm2 }}</p>
                        {% if property.maindescrp %}
                        <p class="text-gray-600">Descripción Mantenimiento: {{ property.maindescrp }}</p>
                        {% endif %}
                    </div>
                    <div>
                        {% if property.currentlease %}
                        <h2 class="text-xl font-semibold text-blue-900">Contrato</h2>
                        <p class="text-gray-600">Inquilino: <a class="text-blue-900" href="{% url 'clients_detail' property.currentlease.id %}">{{ property.currentlease }}</a></p>
                        <p class="text-gray-600">Pago Mantenimiento: {{ property.pay }}</p>
                        <p class="text-gray-600">Póliza Seguridad Social: {{ property.poliza }}</p>
                        <p class="text-gray-600">Depósito: {{ property.deposit }}</p>
                        <p class="text-gray-600">Inicio: {{ property.leasestart }}</p>
                        <p class="text-gray-600">Fin: {{ property.leasend }}</p>
                        <p class="text-gray-600">Incremento: {{ property.increase }}</p>
                        <p class="text-gray-600">Última fecha de Incremento: {{ property.lastincrease }}</p>
                        <p class="text-gray-600">Renovación: {{ property.get_renov_display }}</p>
                        <p class="text-gray-600">Notificación de Renovación: {{ property.notifyrenew }} días</p>
                        {% endif %}

                    </div>
                </div>
            </div>
        </div>
        <div class="px-8 py-4 bg-gray-50 text-right">
            <a href="{% url 'properties_edit' property.id %}" class="bg-blue-900 hover:bg-blue-700 text-white py-2 px-4 rounded transition duration-300">Modificar</a>
            <a href="{% url 'properties_delete' property.id %}" class="bg-red-600 hover:bg-red-700 text-white py-2 px-4 rounded transition duration-300">Borrar</a>
        </div>
    </div>
</div>


{% endblock %}

property/templates/property/properties_list.html
{% extends 'core/base.html' %}

{% block title %}Propiedades{% endblock %}

{% block content %}
<div class="mt-8 bg-white p-8 rounded-xl shadow-md mx-auto pt-4 overflow-x-auto border border-blue-900 max-w-6xl w-full">
    <h1 class="text-3xl text-blue-900 mb-6">Propiedades</h1>
    <a href="{% url 'add_property' %}" class="py-2 px-4 bg-blue-900 hover:bg-blue-700 rounded-full text-white">Crear Propiedad</a>

    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-4 gap-6 mt-6">
        {% for property in properties %}
            <a href="{% url 'properties_detail' property.id %}" class="bg-gray-100 hover:bg-gray-200 p-4 rounded-md">
                <img src="https://media.istockphoto.com/id/1316331605/vector/modern-city-building-exterior-office-center-or-business-house.jpg?s=612x612&w=0&k=20&c=VTJvkEXvS1xS53IxM6p7aJYj2RCZqeYVA57i5WfXkI8=" alt="{{ property.name }}" class="w-full h-40 object-cover object-center mb-4 rounded-md">
                <h2 class="text-blue-900 text-lg font-semibold">{{ property.name }}</h2>
                <p class="text-gray-700">{{ property.state }}</p>
            </a>
        {% endfor %}
    </div>
</div>

{% endblock %}